### ISSUE TITLE
WARNING: Includes root ssh backdoors

### ISSUE THREAD

**Issue by ThuggishNuggets** [sboehler/nixos-config#1]
Anyone looking to use this configuration directly should be aware that it contains backdoors via ssh keys in several different files.

While I assume that you're wanting to share this config as a template and expecting others to modify it for their own purposes, you should at least call this out in the README. It doesn't have to be an index of their locations but at least call out that this is happening.

This was also [an issue in the repo you reference](https://github.com/andir/nixos-gpd-pocket/issues/1) as a template.

**Comment by sboehler** [comment]
Enhanced README: https://github.com/sboehler/nixos-config/commit/e1008853e9e2d4657c4f5c9f8fa59c601b6894a3

If anything, this is a front door, not a backdoor. There is no malicious intent here. Users should know what they are doing and not re-use a config literally.
